### ISSUE TITLE
Infinite loop in viewport.c

### ISSUE THREAD

**Issue by trigger-death** [IntelOrca/OpenRCT2#1183]
I've created instructions to reproduce this infinite loop:

* Enable cheats window.
* Start Electric Fields.
* Turn the park information window to the main page.
* Launch multiple guest trams .
* (You can speed up time here).
* Open some guest windows on the main page of guests going to Rowing Boats 1.
* Game should infinite loop after the guests get on the ride and get off of it, (give it some time).

Preview:
![freeze](http://i.imgur.com/o1eX5zb.png)

**Comment by duncanspumpkin** [comment]
Can't reproduce. Can you provide a save just before it happens?

**Comment by IntelOrca** [comment]
I can't get it to reproduce either, no matter how many times I spam trams and nausea.

**Comment by trigger-death** [comment]
Okay so I think this loop is caused when you have a guest viewport on a guest that's in a rowboat, entering the station when there's already a boat in the station. Notice the bottom left guest window. This has been the case every time I reproduce the bug. SO just keep adding viewports of guests in line.

**Comment by IntelOrca** [comment]
Managed to reproduce it now. Speed up the game on Electric fields, click the boat ride, open the guest list to show people on the ride. Keep opening the peep windows until it freezes.

Looks like x or RCT2_ADDRESS_VIEWPORT_PAINT_X is overflowing or something. It is -32704.

viewport.c:1548
```c
	for (x = RCT2_GLOBAL(RCT2_ADDRESS_VIEWPORT_PAINT_X, sint16) & 0xFFFFFFE0;
		x < RCT2_GLOBAL(RCT2_ADDRESS_VIEWPORT_PAINT_X, sint16) + RCT2_GLOBAL(RCT2_ADDRESS_VIEWPORT_PAINT_WIDTH, uint16);
		x += 32)
{
    ....
}
```

**Comment by IntelOrca** [comment]
Further inspection shows that this may have been caused by opening a peep window while the peep was exiting the ride. The viewport has numbers way out - possible initialisation of the window / viewport or something is wrong with the peep exit code (see the bug @PFCKrutonium found while streaming).

1. The viewport shouldn't be these numbers.
2. The drawing code should probably cope with erroneous data.

![image](https://cloud.githubusercontent.com/assets/1482259/7902547/02f877e4-07b5-11e5-8a21-e87dcdda0f1a.png)
