### ISSUE TITLE
RCT1 Theme wrong preset (Bottom Toolbar)

### ISSUE THREAD

**Issue by danidoedel** [IntelOrca/OpenRCT2#1194]
These settings:
![2015-06-02 02_05_56-openrct2](https://cloud.githubusercontent.com/assets/10995998/7926009/53625624-08cc-11e5-9fd1-111e1f3a6957.png)
should get switched to:
![2015-06-02 02_05_33-openrct2](https://cloud.githubusercontent.com/assets/10995998/7926025/7511a07c-08cc-11e5-9c78-796958a2f72d.png)

Original RCT1 bottom toolbar:
![2015-06-02 01_55_21-rollercoaster tycoon](https://cloud.githubusercontent.com/assets/10995998/7926034/934cc22e-08cc-11e5-924f-114e66541802.png)

**Comment by Gymnasiast** [comment]
What is the third colour used for?

**Comment by danidoedel** [comment]
Why is my RCT1 bottom toolbar looking like that in the picture above then?

**Comment by Gymnasiast** [comment]
How RCT1's bottom toolbar looked has nothing to do with it.

You don't seem to understand how the colours in the settings correspond to the colours in the bottom toolbar. The first colour is of the boxes, the second of the boxes' outline, the third of the background and the fourth of the part rating. Try changing the third colour to something else, green for example and wait until a message appears.

**Comment by IntelOrca** [comment]
I think he is referring to the fact that it shouldn't be transparent.

**Comment by Gymnasiast** [comment]
He also says the third colour should be changed (see the screenshots), which isn't true: RCT1 used a black background when a message appeared.

And about the transparency: I'm not a fan of getting rid of the transparency in the default preset, just because RCT1 used top and bottom toolbars that covered the entire width of the screen. That would make the default RCT1 preset less useful, just for the sake of emulating _every_ aspect of the RCT1. When I introduced the 'RCT1 colour scheme option' I left the transparency as it was because it was an actual improvement.

**Comment by IntelOrca** [comment]
I think he is getting confused about when you hover over an object in map as to when you get a message.

**Comment by danidoedel** [comment]
Yes the third colour is indeed black... my bad...
It's called RCT1 theme and it should look like RCT1 then... but maybe I'm the only person thinking like that ;)

**Comment by Gymnasiast** [comment]
I understand, but RCT2 did introduce some very good changes. It's why they aren't in the RCT1 preset, which aims to pull in the good stuff from RCT1 while also keeping the improvements RCT2 made.

Luckily you can still disable transparency if you really want to go hardcore ;)

**Comment by danidoedel** [comment]
Grrrr :D
Yeah I'm hardcore! ;)

You guys can close this if you want to.
