### ISSUE TITLE
Voided invisible hack

### ISSUE THREAD

**Issue by Belzebub** [IntelOrca/OpenRCT2#1243]
Hi!
I just noticed that when viewing parks from New Element the invisible hack (http://www.nedesigns.com/topic/29202/updated-invisible-hut-tutorial-images/) isn't displayed correctly, as everything that shouldn't be visible is invisible.
We use this hack to remove ride entrances/exits, track that shouldn't be visible and so on...
Is this on purpose, is another way getting things invisible planned or is this a bug?
Thanks!

**Comment by duncanspumpkin** [comment]
Yes this is a bug, I noticed this a couple of weeks ago. I'll try find out the source. As for purposely making things invisible. I might be able to come up for a way to draw entrances/exits invisible that could be portable back to rct2 but it will be a little hacky.

**Comment by duncanspumpkin** [comment]
Would it be possible to provide a plain park where i can zoom in on the center and all there is in the main window is a ride of minimal length with this invisible entrance.

**Comment by duncanspumpkin** [comment]
Okay so I've finally worked it out. So here is how the invisible entrance works.

Map elements will be in the following order:

* any/none elements
* bugged element
* invisible element
* any other elements but they wont get drawn

Now the bugged element has an undefined type. To understand this I first need to show how a map element type is usually worked out.
```
map_type = 0xQQTTTTDD
Q = quadrant,
T = type,
D = direction
```
There are normally only 8 types:
```
enum {
	MAP_ELEMENT_TYPE_SURFACE = (0 << 2),
	MAP_ELEMENT_TYPE_PATH = (1 << 2),
	MAP_ELEMENT_TYPE_TRACK = (2 << 2),
	MAP_ELEMENT_TYPE_SCENERY = (3 << 2),
	MAP_ELEMENT_TYPE_ENTRANCE = (4 << 2),
	MAP_ELEMENT_TYPE_FENCE = (5 << 2),
	MAP_ELEMENT_TYPE_SCENERY_MULTIPLE = (6 << 2),
	MAP_ELEMENT_TYPE_BANNER = (7 << 2)
};
```
Note that banner is the highest at 7 and only takes up 3 bits. That highest bit is unused.
The bugged element has a type of (15 << 2). This is clearly not on the list.
I'm not sure why the code never failed with this undefined type but I can at least explain why the drawing code acts odd. The drawing takes the map_element type and looks up a list of drawing functions and runs the correct one.
```
// Size 8
drawing_functions = {
 draw_surface,
 draw_path,
 draw...,
 draw_banner
};

drawing_functions[ map_element type ]( vars... );
```
But what happens with the undefined type is that it walks off the end of this array and into another completely separate set of functions. It just so happens at the end of drawing functions array is the map animation functions.
```
// Size 8
drawing_functions = {
 draw_surface,
 draw...,
 draw_banner
};
// Size 14
animation_functions = {
 animate_entrance,
 animate_queue,
 animate_small_scenery,
 park_entrance,
 track_waterfall,
 track_rapids,
 track_onridephoto,
 track_whirlpool, <= 7
 track_...,
 ...
};
```
So our undefined element is 15 so it goes past the drawing functions and into the 7th animation function. Now this function iterates through all elements at an undefined location (since its been passed garbage for x and y coordinates) until it gets to a track piece of whirlpool type. But more often than not it will not find a track either way not important what it does. The important thing is it will set the map_element to the element at the end of the (unknown) tile. When the function returns it comes back to the drawing code with this map_element set to a undefined tile. It then increments past this to the next tile which again is at an unknown coordinate and tries to continue drawing. Since the coordinates at this point are so broken it eventually exits without drawing anything.


So after all that my solution is if its an undefined type skip the next element.
