### ISSUE TITLE
Filename for (new file) in save dialog changes to "autosave" when autosave is enabled and has triggered since last manual save

### ISSUE THREAD

**Issue by rctdude2** [IntelOrca/OpenRCT2#1265]
Self explanatory. Re-saving under a different name updates it to that name (which is correct behavior, it just shouldn't change to "autosave").

**Comment by Gymnasiast** [comment]
I think that might have been introduced by #1244.

**Comment by LRFLEW** [comment]
Yeah, I definitely introduced this behavior in #1244. I wasn't thinking of the autosave feature when i was implementing that. The question is, is this the expected behavior for LOADING autosaves? If you select "autosave.sv6" as the save to load, should the (new file) option show "autosave" as the default option? If not, then the correct behavior may be difficult to create, as the original save name (aka `gScenarioSaveName`) is not stored with the autosave as of now.

**Comment by marcotc** [comment]
How about naming the autosave "originalSaveName_autosave.sv6", so that you can derive the name when the autosave has been loaded. Still, it can fail to find the "_autosave" suffix, so a fallback is still necessary.

**Comment by IntelOrca** [comment]
The filename should only change to your last **manually** set filename.
