### ISSUE TITLE
Load landscape from convert saved game step has problems

### ISSUE THREAD

**Issue by IntelOrca** [IntelOrca/OpenRCT2#631]
If you try to convert a saved game to a scenario and then load a landscape from the scenario editor, the previous step button is not shown. Sometimes it shows after stepping forward. Then stepping back to the object selection step can cause a fatal crash.

**Comment by duncanspumpkin** [comment]
This is actually a bug in object selection as a whole. What is happening is that the game is crashing because the required object is not loaded. When the object selection window is shown it first of all unloads all objects. It then works out which objects are in use on the map and reloads those objects. This second part is failing. 

I am not sure why the next step is not showing at all times though.

**Comment by duncanspumpkin** [comment]
Possible functions that may know the source of this issue 0x006ab211 and 0x006aa770

**Comment by IntelOrca** [comment]
Did this happen in vanilla RCT2?

**Comment by duncanspumpkin** [comment]
No this is a new "feature" sadly. I think I have an idea why it might be happening but was too tired yesterday to work it out.
