### ISSUE TITLE
Add New Game Option to Save Menu/Make Quit Game Button Exit the Game

### ISSUE THREAD

**Issue by pizza2004** [IntelOrca/OpenRCT2#688]
In RollerCoaster Tycoon there was a button that said New Game which took you back to the main menu and the Quit Game button actually quit the whole game.  In RCT2 when you click Quit Game it takes you back to the menu.  I'd just like an option to quit the game entirely.

**Comment by Gymnasiast** [comment]
Good idea. The current button could be renamed 'Quit to menu' and the new button could be named 'Quit OpenRCT2', for clarity.

**Comment by vzybilly** [comment]
Another good idea would be to have a spacer between 'Quit Park' and 'Quit Game' and a warning Y/N Popup for the game asking if they are sure they want to quit OpenRCT2...

**Comment by pizza2004** [comment]
Quit Park or Close Park might be better wording than New Game.  Possibly just call it Close Game and put it up by Load Game and Save Game like New Game was in RCT 1.

**Comment by danhere** [comment]
I know it's trivial but "Close Park" has negative connotations to actually close the park down in game. Maybe "Leave Park" and "Quit OpenRCT2" might work better.

**Comment by IntelOrca** [comment]
OpenTTD uses **Abandon game** and **Exit**

**Comment by pizza2004** [comment]
That could also work.

**Comment by RollingStar** [comment]
What is up with all of these issues and pull requests insisting on regressing back to the RCT1 era? The RCT2 way requires less buttons, which is superior. Every additional menu item exacts a thinking cost on the end-user. Keep it simple, please. Or at least do what I recommended in the other pull request (adding an RCT1-style finances button): have an option to keep behavior similar / identical to normal RCT2.

Like that other pull request, I argue that the consolidation of menu items from RCT1 to RCT2 is the result of user testing and feedback, rather than some arbitrary decision.

**Comment by IntelOrca** [comment]
@RollingStar The research button and its RCT1 style dialogue in my opinion is necessary in games where there is no finance. This is because you are unable to select the research order priority just because its part of the finance window which is disabled - and it won't make sense to have the finances window with only one tab which isn't really to do with finance.

As for the finance button being on the toolbar, this makes no difference in gameplay. Nevertheless both buttons will have an option available which is opt-in (default is RCT2 like). Sometimes however, it can overcomplicate the game if you have too many settings, this article related to Android settings is very interesting (http://developer.android.com/design/patterns/settings.html) Therefore I vote that the additional exit game (application) should exist and not have a setting to disable it.

**Comment by Gymnasiast** [comment]
Has been implemented recently, so this can be closed.
