### ISSUE TITLE
Height marks show up in feet even when the metric system has been selected

### ISSUE THREAD

**Issue by Gymnasiast** [IntelOrca/OpenRCT2#700]
![schermafdruk van 2015-01-17 20 29 24](https://cloud.githubusercontent.com/assets/1478678/5790058/cc2b2ff4-9e87-11e4-847b-e5e56c6cff55.png)

Measures in other places seem to show correctly in metric.

**Comment by adrian17** [comment]
Caused by [these lines](https://github.com/IntelOrca/OpenRCT2/blob/develop/src/config.c#L838-843) being absent in the new config loading code. Also, [this line](https://github.com/IntelOrca/OpenRCT2/blob/develop/src/windows/options.c#L794) is wrong, it should be `gGeneral_config.measurement_format`.

**Comment by duncanspumpkin** [comment]
@adrian17 i've made your suggested changes and it all works fine after those changes.

**Comment by adrian17** [comment]
Thanks. (I didn't make a PR myself as I wasn't sure what to do with lines 838 and 843, which also seemed to be absent).

**Comment by duncanspumpkin** [comment]
L843, 0x009AA00D controls if this is the first time loading up RCT2 and modifies the object loading screen but since we have modified how the object loading works there is no difference between a first and second time load.

L843, 0x009AB4C6 controls if this is the first time running the config options to force it into the first time  load of config, pretty similar to 9aa00d. Both not really required anymore.

**Comment by Gymnasiast** [comment]
Tested it, looks like it's solved. :)
