### ISSUE TITLE
The arrow button on rides / stalls takes the view underground on above-ground rides

### ISSUE THREAD

**Issue by RollingStar** [IntelOrca/OpenRCT2#705]
[Relevant save file](http://www.mediafire.com/download/hk5qsb9qg3ahwiq/Ghost_Town_RollingStar.SV6)

Open the save file. Click on the swinging ship or the burger bar. Click on the four arrow button.

![image](https://cloud.githubusercontent.com/assets/4810902/5793788/febc924a-9f1e-11e4-8e31-6609b958ca34.png)

The game is placed in underground / inside view. This does not happen on regular RCT2.

**Comment by duncanspumpkin** [comment]
This used to happen on peeps as well I think the issue was something to do with not masking the height to remove extra surface information. Should probably change window/ride.c to use window_scroll_to_viewport instead of rewritting that function for WIDX_LOCATE.

**Comment by IntelOrca** [comment]
Also I think many of these masking operations should be changed to functions calls. Take **map_element_get_terrain** and **map_element_set_terrain** as an example. These will be inlined by the compiler so there should be no performance penalty in the long run.

**Comment by duncanspumpkin** [comment]
Well this issue isn't actually because of a masking issue. For whatever reason the original code for the ride window puts the z coordinate into a different address compared to all other windows. Due to code reuse in OpenRCT2 the z coordinate is now in the normal location and that causes locate to fail as it has been customized for original RCT. I'm just going to remove the custom version in the ride window and make it use all of the normal address's.
