### ISSUE TITLE
Crash with placing big roller coasters

### ISSUE THREAD

**Issue by RM87** [IntelOrca/OpenRCT2#713]
Non constant steps to reproduce:
saved game: Botany breakers http://web.zone.ee/rmihkel87-1/orct2/Botany_Breakers_c.SV6
select a big roller coaster (one of the big wooden coasters that fits into the free area or hypercoaster) for building.
Try to find a place where it is buildable. Move the mouse around  for some time. Find a different place. Select a different design. 
It should have crashed by now.

Sadly I could not find way to crash it every time the same way. But it did crash every time within a minute or 2.

**Comment by AaronVanGeffen** [comment]
Sounds like what @duncanspumpkin is trying to fix in #712.

**Comment by duncanspumpkin** [comment]
Its not actually related. The 712 bugs are to do with the preview window this bug is in the track place window. There is another little bug in the track place code hopefully thats the only issue. It would only present when there is a track which is bigger than the preview screen size. I've rolled the fix into #712.

**Comment by duncanspumpkin** [comment]
@RM87 can you have a play about with the latest build and confirm if the bug is now fixed.

**Comment by RM87** [comment]
Seems to work fine now.

Thank you!
