### ISSUE TITLE
Interface menus have no animation when game is paused

### ISSUE THREAD

**Issue by yayachiken** [IntelOrca/OpenRCT2#716]
commit a7a89fcf0f8a87101ebbb1ad4beff13d56d789a0

When pausing the game, the animation in the menus freezes as well.

Expected behaviour: Even though the game itself is paused, the interface should not be affected.

Steps to reproduce:
1. Open the ride building menu, and observe that the animation of the ride category icon is animated. If you open the thrill ride menu, the animation is the easiest to observe.
2. Pause the game. The animation freezes.
3. If the category is switched while the game is paused, the animation will reset to the first frame.

I do not remember this being the same in RollerCoaster Tycoon 2, but I can not confirm it 100% either since I currently can not play the original RCT2 on my Linux box.

**Comment by Gymnasiast** [comment]
Yes, this is the same in original RCT2.

**Comment by duncanspumpkin** [comment]
Its by design. There is a window update function that is fired every tick even when paused and another that stops when paused. For whatever reason RCT2 uses the version that stops when paused.

**Comment by IntelOrca** [comment]
I don't know what a user experience expert would say. I guess it makes it more obvious that the game is paused and that construction is not possible if all UI animations pause.

**Comment by yayachiken** [comment]
As it's not a bug I think it would still be nice if this issue could be kept as a low-priority enhancement request. Leaving the interface animations running would look more polished imo.

**Comment by Gymnasiast** [comment]
From an UX viewpoint* I would say the current situation makes the interface less consistent. Seeing whether the game is in pause mode is clear enough since the pause button is pressed, the rides and people don't move and there is no music.
I think the developers only put window actions they found important under the 'always-even-when-paused' function.

Now, you could also argue that stopping window animations together with the rides and people in pause mode _is_ consistent. But if build-in-pause-mode gets implemented that doesn't really apply anymore.

(* I have had UX as a subject two years ago; I'm not an expert but not a novice either.)

**Comment by yayachiken** [comment]
Also there are menus that are still functional in pause mode, but still have paused animations.  For example research and loan management.

**Comment by Gymnasiast** [comment]
Has been implemented recently, so this can be closed.
