### ISSUE TITLE
??? Instead of Text

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#743]
![scr1](https://cloud.githubusercontent.com/assets/3945538/6033881/b0c3033a-abe9-11e4-8a83-6b78761083cc.png)

I am not sure if this is from my launcher (I don't see how, all I am doing is launching OpenRCT2...) or a Vanilla OpenRCT2 Bug, but occasionally things like this will happen. If it is my launcher, any idea's how to fix it?

Edit: Confirmed it does happen occasionally when not using launcher as well, is Vanilla bug,

**Comment by AaronVanGeffen** [comment]
Looks like a localisation problem. Can you verify the language files are up-to-date as well?

**Comment by JarnoVgr** [comment]
You're probably using the 'English (US)' language instead of the 'English (UK)' version, which is more up to date.

**Comment by ThomasdenH** [comment]
It would be handy to fall back to (UK) regardless of the original language. That way the user has an idea what the button does.

**Comment by duncanspumpkin** [comment]
It currently falls back to the original RCT2 text. Due to the way we have added the new text it would be a bit annoying to fall back to english (UK). Maybe when we switch to a better method for storing new strings we can do that but until everything text related is using the new code we can not do that.

**Comment by PFCKrutonium** [comment]
Ye, Confirmed that it is the language...
