### ISSUE TITLE
Mixer expects UTF8 filenames.

### ISSUE THREAD

**Issue by IntelOrca** [IntelOrca/OpenRCT2#744]
The following functions expect UTF8 encoded filenames.
```
bool Sample::Load(const char* filename)
bool Sample::LoadCSS1(const char* filename, unsigned int offset)
```

```Sample::Load``` is not so straight forward to change, as it is using SDL's load wave function which requires an SDL file structure. The best thing to do right now is probably convert the filename from extended ASCII to UTF8 for the functions above and use the utf8 typedef instead of char *.

This was the leading cause of #702.

**Comment by pGore33p** [comment]
You are bloody right with this issue, it worked on a different directory with no special characters. As I live in Czech Republic (and I am using dad's computer), I can't change the language because it will make him angry. Czech Republic has these special characters such as š, č, ř, ý, ž, etc. I am not exaggerating... almost every country has special characters... I am pretty sure this can't be fixed easily.

**Comment by IntelOrca** [comment]
@pGore33p Could you please confirm whether this is fixed?

**Comment by pGore33p** [comment]
@IntelOrca Yes it works.
