### ISSUE TITLE
RC Designer bug

### ISSUE THREAD

**Issue by pGore33p** [IntelOrca/OpenRCT2#747]
I found a very strange bug, and needs to be fixed immediately...
In our Roller Coaster Designer, I found out that no roller coasters are showing in the tab after you selected on step 1. It shows nothing.... literally. After you go to step 1 again, they are unselected. I thought wtf is wrong with it? :octopus: Also they are shuffled, they are not sorted alphabetically.

Here is the video recorded on my tablet (sorry for the weird rotation, the tablet recorded it like that): 
https://onedrive.live.com/redir?resid=69986CE18955BE7%21390 (tell me if the link is wrong)

**Comment by duncanspumpkin** [comment]
The none alphabetical issue is because of something i changed a while back. I didn't realize it was used for the object list this way and I have spent a while thinking of ways to bring it back. It's not too easy to fix without having to rewrite a bunch. I haven't looked at the rollercoaster designer at all but its possible I might have broken it with the changes to the tracks. I will try look at it tonight.

**Comment by pGore33p** [comment]
@duncanspumpkin OK... I found many people use it tho I prefer the workbenches more. But I still use the Designer for nostalgia sake.

**Comment by duncanspumpkin** [comment]
Yup regression is caused by my track refactor. Shouldn't take too long to find the cause.
