### ISSUE TITLE
OpenRCT2 logo required

### ISSUE THREAD

**Issue by IntelOrca** [IntelOrca/OpenRCT2#750]
Before our first pre-release, we need to create a square logo for OpenRCT2 which will be used for the executable / application icon. If there is anyone experienced in illustration art or knows anyone that is and who is up for the task, an SVG submission would be welcome.

It can be based on one of the original icons for RCT if desired. I also think the icon should have a transparent background with some sort of border rather than a opaque square.

Thanks.

**Comment by IntelOrca** [comment]
Perhaps a new high quality vector graphic version of this?
![image](https://cloud.githubusercontent.com/assets/1482259/6097776/aa9ee81c-afc1-11e4-9597-c8f2a4f512d3.png)

**Comment by PFCKrutonium** [comment]
![icon_vector](https://cloud.githubusercontent.com/assets/3945538/6097874/11fdb672-af9b-11e4-8879-720d7d79746c.png)

How does this look?

**Comment by runelaenen** [comment]
Looks like a generated png2svg image :p

**Comment by PFCKrutonium** [comment]
And you may be right. ;)

**Comment by PFCKrutonium** [comment]
https://mega.co.nz/#!GB80kDpA!YCalsqgCzL2DhaCrllX_pBMLLE9CJn7N3O_-qFt5B6Y
The svg file.

**Comment by RollingStar** [comment]
[Potential logo source](http://pixabay.com/en/roller-coaster-tracks-swirly-ride-32758/)? ([Original SVG](https://www.mediafire.com/?e3vxqcy6duwn12w))

It's too busy looking right now (looks to be based on a real photo) but I took out just the coaster part and I'm working with it.

![image](https://cloud.githubusercontent.com/assets/4810902/6098084/8e44262a-afa1-11e4-98cf-7deff970a329.png)

[SVG](https://www.mediafire.com/?e3vxqcy6duwn12w)

**Comment by AaronVanGeffen** [comment]
Oh, I'm liking your idea, @RollingStar!

**Comment by zsilencer** [comment]
![openrct2logo](https://cloud.githubusercontent.com/assets/5456638/6102199/8bc5bfc4-afee-11e4-8129-de8db747da88.png)

?

**Comment by Gymnasiast** [comment]
@PFCKrutonium: Perhaps putting 'Open' in the banner would be a nice touch?

@RollingStar: Of the current variations I think the third small one looks the best. But personally I think one color might be a bit too little.

@zsilencer: I think 'Open' and 'RCT2' might be too short to be separated. Perhaps putting them behind each other would look better.

**Comment by Yazzaa** [comment]
Hi! I am a full time graphic designer and I would like to help you get a nice icon. But I have a few questions. 

First of all, am I correct in thinking this is the icon you click when you launch the program and not the logo you see in the splash screen once you've started the game? 

Do you want the words "openRCT2" or "rollercoaster tycoon 2" in the icon?

Will any square SVG file work or are there some limitations I am not aware of?

I can make time to work on this somewhere this week. I might base it on the origional pink and yellow RCT logo. I really like that one. Either that, or updated icons similar to the ones shipped with the original game. (this one http://www.rctland.eu/Toppuntvan/RCThoeenwaarom/hoeenwaarom1.jpg)

Let me know.

**Comment by IntelOrca** [comment]
@Yazzaa It will be the official logo for the project and game. Used as the game icon that you click on or see on the windows start screen. I don't mind what you base it on, I am open to any ideas. Thanks for your input.

**Comment by IntelOrca** [comment]
A square SVG, no other limits. It can then be exported as PNG to different sizes.

**Comment by drewmo** [comment]
Here are few exported to .pngs, I have a single [.svg](https://docs.google.com/file/d/0B6ImY5hmh8v3clZxSzZEQTFuWWM) with all the variants in them:


![orct2logos_04](https://cloud.githubusercontent.com/assets/7915652/6132523/d86c0c42-b107-11e4-8c7f-61f0eba79573.png)![orct2logos_05](https://cloud.githubusercontent.com/assets/7915652/6132525/db91ebe4-b107-11e4-8b6f-4221f4de8e0d.png)![orct2logos_06](https://cloud.githubusercontent.com/assets/7915652/6132526/dce23fa8-b107-11e4-8f4f-bab115d4e721.png)![orct2logos_07](https://cloud.githubusercontent.com/assets/7915652/6132528/de1166e2-b107-11e4-830b-c16254040029.png)
![orct2logos_02](https://cloud.githubusercontent.com/assets/7915652/6132521/d677ea5a-b107-11e4-97d1-876fbe2316c5.png)![orct2logos_08](https://cloud.githubusercontent.com/assets/7915652/6132529/df3e4e04-b107-11e4-8635-627ca17cd895.png)![orct2logos_09](https://cloud.githubusercontent.com/assets/7915652/6132530/e131e7d4-b107-11e4-98b3-3ac33d4c0d1b.png)

Here is my favorite (changed a little from above):

![orct2pick](https://cloud.githubusercontent.com/assets/7915652/6133027/ce9481b4-b10b-11e4-950f-0abc41daa5fe.png)
[SVG](https://docs.google.com/file/d/0B6ImY5hmh8v3dUVQOHNXRFVtM0E)
*There are some issues viewing it in inkscape, since I used Illustrator to create the file.

**Comment by RollingStar** [comment]
One logo was posted on [Reddit](http://www.reddit.com/r/rct/comments/2vbm9a/openrct2_logo_required/cogviaf):

![image](https://cloud.githubusercontent.com/assets/4810902/6134622/abc8087a-b130-11e4-9137-19b9d7b850cb.png)

@Yazzaa, I suggest you don't base it too heavily on existing RCT art. The logos are trademarked so we should avoid anything "[confusingly similar](https://en.wikipedia.org/wiki/Confusing_similarity)" to any trademarked RCT art. @zsilencer has a good logo but it might be a trademark issue. I also think the logo should look good at a resolution of 48x48 pixels and above. I would *definitely* stay away from using trademarked phrases like "RollerCoaster Tycoon" in the logo. "RCT2" on the other hand is too short to be trademarked, so if the logo calls for it, it can be used. (But, IMO, the best computer icons don't have words on them.)

@drewmo, I like that logo. :) At 48px, the text looks a little small. Could you try one with just "2" in the middle, and no other text?

![image](https://cloud.githubusercontent.com/assets/4810902/6134757/966ae136-b131-11e4-96bb-63958959e98f.png)

I pick 48px because that's how big the icons are on my Windows 8 desktop (1600x900 monitor).

I'm just a fan of the project, not the leader, so you can do what you want, but those are my ideas.

**Comment by IntelOrca** [comment]
I think something based on the Helter skelter (ride) would be a good candidate. It is seen a lot throughout the game and identifies the type of game well.

**Comment by xzbobzx** [comment]
How about something along the lines of this?

![Helter Skelter](http://i.imgur.com/H2RMCLz.png)

Obviously it's a work in progress.

**Comment by IntelOrca** [comment]
@xzbobzx Nice, perhaps you could try reducing the contrast by using lighter colour shades and reduce the thickness of the lines, particularly the inside ones. Also don't abbreviate "open", keep it "OpenRCT2".

**Comment by xzbobzx** [comment]
@IntelOrca How about this?

I'm not too sure about how (or if) we'd want to have text on the logo, but I have this so far:
![Helter Skelter 3](http://i.imgur.com/Ce4XLwL.png)

**Comment by runelaenen** [comment]
That looks awesome :D
But personally I would add text

**Comment by xzbobzx** [comment]
@runelaenen 

![HelterSkelter4](http://i.imgur.com/BhdaW8m.png)

**Comment by Gymnasiast** [comment]
Personally I would put the text on one row and on a sign . :)

**Comment by xzbobzx** [comment]
@Gymnasiast That's a good idea! I'll try some things out when I get home.

I wasn't all too happy about the plain white letters myself.

**Comment by duncanspumpkin** [comment]
I like that last one the best but the font and the colours are not the best. What does it look like as a small icon?

**Comment by xzbobzx** [comment]
@duncanspumpkin It's surprisingly readable as small icon:

![HelterSkelterIcon](http://i.imgur.com/ouOq93W.png)

I'm all open for suggestions, though. What do you think the colors should be like?

**Comment by duncanspumpkin** [comment]
I'm not really sure. I've never been the best at design. The flag doesnt stand out very well. What would it look like if you went for a similar style to the OpenTTD logo and gave it a diamond background?

**Comment by Wopian** [comment]
@xzbobzx the icon looks far better without the white text/black text on brown sign on smaller sizes.

**Comment by IntelOrca** [comment]
You should have light foreground text on dark background. Try making the text white.
Also, the top of the slide cuts off abruptly, it should probably start at the left side of the door.

**Comment by xzbobzx** [comment]
So now I have these:

![s](http://i.imgur.com/pA8OZ2h.png)
![s](http://i.imgur.com/LNk4lFo.png)
![s](http://i.imgur.com/5IdKrYx.png)

Big versions:
http://i.imgur.com/HfEIrZT.png
http://i.imgur.com/JTCWF0n.png
http://i.imgur.com/D4R7shH.png

I'll get right to work on that slide stopping near the door

**Comment by duncanspumpkin** [comment]
I like that first diamond one. Thats what I was imagining.

**Comment by runelaenen** [comment]
The first diamond one looks great, only white text like in the second one would be better imo

**Comment by mrtnptrs** [comment]
Like the first diamond one the most, but couldn't you make it so, that the flag doesn't stick out of the diamond?

**Comment by mkoch227** [comment]
@xzbobzx the first one looks fantastic :grinning:

**Comment by Wopian** [comment]
:+1: for 3rd one.

**Comment by IntelOrca** [comment]
@xzbobzx Looks okay, you should now modify it so it looks like a cap, rather that a straight cut at the colour division line.

**Comment by vzybilly** [comment]
I like the first one as well but around 20x20 it starts to be unrecognizable and with my quick launch bar thing currently using 16x16 icons, it just ends up as a orangeish blob. the last one with out the background really does continue to show the slide even at the 16x16. I'm also pretty sure that if I have 16x16 then other people also would...

So, while the first looks great, to keep it visible, the last wins.

I would like to see the diamond be a different colour and see how that looks with the slide, maybe a contrasting colour to help bring out the slide at low res? I'll see about playing abit and I might find a good color for it, to help out...

**Comment by runelaenen** [comment]
Keep in mind that when using an .ico file you can provide different versions for different sizes.

**Comment by IntelOrca** [comment]
@runelaenen You're right... this is a common problem... smaller versions of logos tend to be created which is more suitable for its size.

**Comment by vzybilly** [comment]
I think my OS (Lubuntu, Linux) just uses PNGs and scales but I'll take a peak if I can...

**Comment by runelaenen** [comment]
Yeah .ico is mainly used in windows, but Linux should be able to handle .ico icons, don't know anything about OS X though...
Although many devs like us run Linux (me too), most of the users will be running windows I think...

**Comment by PFCKrutonium** [comment]
Can confirm, most users will be using Windows. And Linux can read .ico files, though I don't know about as icons. If you apply some Wine icons will work in EXE's... 

I have a Kali laptop, so I can test if someone tells me how. (I don't use Linux/Kali a whole lot).

**Comment by IntelOrca** [comment]
OSX uses its own icon file format [.icns](http://en.wikipedia.org/wiki/Apple_Icon_Image_format) which supports different sizes.

**Comment by xzbobzx** [comment]
How's this?

![s](http://i.imgur.com/BqcPLk8.png)
![s](http://i.imgur.com/A2G4v9X.png)
![s](http://i.imgur.com/rzAbc25.png)

Big versions:
http://i.imgur.com/c0DnWw4.png
http://i.imgur.com/pskrgPn.png
http://i.imgur.com/RHZxQdQ.png

I've added a thing to the top of the slide, too. It's a bit weird though:
![thing](http://i.imgur.com/RHZxQdQ.png)

I really like how the big diamond one looks.
![s](http://i.imgur.com/c0DnWw4.png)

**Comment by Gymnasiast** [comment]
Linux icons are either in different sizes of PNG, or in SVG. I have never seen a program on Linux use .ico files as its icon, and I doubt whether it will work. Using an SVG is probably the best choice.

**Comment by IntelOrca** [comment]
@xzbobzx Very nice, the slide really stands out against the sky background. I think for 32x32 or less, it should probably not have the text, just the diamond and slide.

**Comment by xzbobzx** [comment]
Alright, so now we have this:

![done](http://i.imgur.com/oATZsnV.png) (1024px)
![done](http://i.imgur.com/YECxmIo.png) (1024px)
![done](http://i.imgur.com/R5mz3ft.png) (128px)
![done](http://i.imgur.com/vkXKegf.png) (64px)
![done](http://i.imgur.com/IIYyiq5.png) (48px)
![done](http://i.imgur.com/5KYQn2S.png) (32px)
![done](http://i.imgur.com/AdUxro0.png) (16px)

What do you guys think?

**Comment by sjoerddebruin** [comment]
@xzbobzx: maybe 48 also without text...

**Comment by xzbobzx** [comment]
@sjoerddebruin Well, sure, but that's all up to whatever icon format they're going for. SVG drawings can be scaled anyway you like.

**Comment by vzybilly** [comment]
Looks amazing, for my the 48 is still quite readable and it reminds me nicely of what game it is even with out the text, which means it's doing its job~

**Comment by Wopian** [comment]
![](https://camo.githubusercontent.com/623316b6b3b62c7c24d2b017015a6459be97c927/687474703a2f2f692e696d6775722e636f6d2f373932554a5a642e706e67) this looks beautiful :heart_eyes:

**Comment by marcotc** [comment]
Windows 7 uses 48x48 by default. This is how it looks like in my desktop.

​
We might want to move the text or remove it from the Windows shortcut when
we have one.

On Thu, Feb 12, 2015 at 4:16 PM, James Harris <notifications@github.com>
wrote:

>
> <https://camo.githubusercontent.com/623316b6b3b62c7c24d2b017015a6459be97c927/687474703a2f2f692e696d6775722e636f6d2f373932554a5a642e706e67>
> this looks beautiful [image: :heart_eyes:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IntelOrca/OpenRCT2/issues/750#issuecomment-74154397>.
>



-- 
Marco Costa

**Comment by marcotc** [comment]
Btw, great work guys!

On Thu, Feb 12, 2015 at 4:50 PM, Marco Costa <mmarcottulio@gmail.com> wrote:

> Windows 7 uses 48x48 by default. This is how it looks like in my desktop.
>
> ​
> We might want to move the text or remove it from the Windows shortcut when
> we have one.
>
> On Thu, Feb 12, 2015 at 4:16 PM, James Harris <notifications@github.com>
> wrote:
>
>>
>> <https://camo.githubusercontent.com/623316b6b3b62c7c24d2b017015a6459be97c927/687474703a2f2f692e696d6775722e636f6d2f373932554a5a642e706e67>
>> this looks beautiful [image: :heart_eyes:]
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/IntelOrca/OpenRCT2/issues/750#issuecomment-74154397>.
>>
>
>
>
> --
> Marco Costa
>



-- 
Marco Costa

**Comment by IntelOrca** [comment]
We can omit the text from the 48x48. It will say OpenRCT2 under the icon anyway.

**Comment by RollingStar** [comment]
@xzbobzx, I'm neutral on the diamond. It's an awesome logo though. Not every logo needs a background. Inkscape doesn't have one for example.

![image](https://cloud.githubusercontent.com/assets/4810902/6180317/28075636-b2f1-11e4-8da8-8a81ad9a8820.png)

IMO, the diamond makes the icon too busy. But I don't care too much because Windows lets you change EXE icons *and* one EXE can bundle multiple icons. Here's RCT2's selections (used for different program features).

![image](https://cloud.githubusercontent.com/assets/4810902/6180466/3c83449c-b2f3-11e4-90b5-46c8df3a2cbe.png)

Here's how your logo looks as a Windows desktop shortcut.

![image](https://cloud.githubusercontent.com/assets/4810902/6180389/298f5d36-b2f2-11e4-91de-b96eb1926038.png)
![image](https://cloud.githubusercontent.com/assets/4810902/6180391/2b9f8cf4-b2f2-11e4-8373-32b57529fb4e.png)

I second that text should not be on the 48px icon.

**Comment by IntelOrca** [comment]
@RollingStar I think your pictures prove that it should have a background (the diamond), otherwise the slide might not show up very well depending on the user's desktop background.

**Comment by xzbobzx** [comment]
@marcotc Hey damn, I never even thought of the shortcut thingy being put over the icon. Good catch!

@IntelOrca If you're all right with the logo as it is, I can give you the SVGs and you can work on getting it into icon formats.

**Comment by kevinburke** [comment]
@xzbobzx maybe a different font? the current one feels a little blah


--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by xzbobzx** [comment]
@kevinburke It's just good old Verdana I'm using. I personally think it's best to keep the font simple and readable. If you have a font in mind I'd be happy to hear it, though,

**Comment by runelaenen** [comment]
@xzbobzx Ubuntu is a nice font? I don't use the OS, but I love the fonts.
http://font.ubuntu.com/
![Image of Ubuntu font](http://ulyssesonline.com/wp-content/uploads/2010/12/ubuntufont-e1292957888924.jpg)

**Comment by xzbobzx** [comment]
@runelaenen Nice! I'll get on it back home. It looks good, nice and clean.

**Comment by xzbobzx** [comment]
Here it is with Ubuntu:

1024px:
![1024](http://i.imgur.com/QwA8biF.png)

128px:
![128](http://i.imgur.com/uvbM6nc.png)

For reference, here is the Verdana version in 128px:
![128](https://camo.githubusercontent.com/0ad06770237809cc39bef4fef5b7a1dec46903cc/687474703a2f2f692e696d6775722e636f6d2f49626b7a5842512e706e67)

**Comment by dpk** [comment]
How about dropping the banner with the game name altogether? It will only get harder to read at small sizes, no matter what typeface you try. (If it must be anywhere, how about writing it in tiny letters on the flag, so it's a nice easter egg for those who care to view the icon at a large enough size?)

**Comment by xzbobzx** [comment]
Putting the name in the flag looks a bit... weird, to be honest:
![s](http://i.imgur.com/hAEuoRi.jpg)

It's a fun idea, but I'm afraid it's a bit hard to implement.
However, removing the banner altogether woud probably work very well:

128px:
![128](http://i.imgur.com/rV9J3Ko.png)

64px:
![64](http://i.imgur.com/Rb1zDAO.png)

48px:
![48](http://i.imgur.com/MPBS6WG.png)

**Comment by IntelOrca** [comment]
@xzbobzx Is it possible to make the logo, less cartoon like. It looks okay 64x64 down, but the larger versions don't quite fit as well as the original RCT logo did. Imagine if the logo was to overlay somewhere on the title screen... it would look out of place. It might be due to the black lines between the colours, which you otherwise can't see on the smaller versions. Perhaps also try to give the logo a more 3D appearance too.

**Comment by xzbobzx** [comment]
@IntelOrca Above 64px you might as well make an entirely new and different icon in the likes of this, which is actually more of a logo than an icon:
![rct2](http://fc03.deviantart.net/fs71/f/2013/108/1/1/rollercoaster_tycoon_2_icon_by_thedoctor45-d3hzli0.png)

Without actually making a 3d model it'd be pretty hard to make it look more 3d.

Here's my icon without lines, if that's what you're after:

1024:
![1024](http://i.imgur.com/RU9pC2W.png)

128:
![128](http://i.imgur.com/hzC4KCG.png)

Maybe some clouds in the background might be nice?
The problem with vector images is that there's a limit to how realistic something can be, before it starts to get very hard to make it look more 'real'/3d/whatever.

You might want to look into a logo for anything above 64/128, because I do agree it starts to look a bit cartoony above certain sizes.

**Comment by IntelOrca** [comment]
Well I don't mean realistic in that its using a complicated illumination formula, I just mean something that might look good when over the graphics you see in RCT. It is probably just a case of playing without with the shading until it looks good.

Another idea is combining @RollingStar's logo idea with this one, by having the coaster track circle the slide for a large version of the logo that could appear on the sliding intro screen.

**Comment by xzbobzx** [comment]
Hmm I may have another idea...

I'd have to play with the shading a bit to see if I can get that better looking, but meanwhile:

How about we give the big versions more rides? Like a ferris wheel and a rollercoaster in the background? Maybe even an observation tower.

I'm not sure if RollingStar's logo would fit the style, but I'm sure I can make a bunch of rides to place behind the slide. I'll probably make the slide smaller in the process to give the other rides some more room.

How's that sound?

**Comment by dpk** [comment]
At smaller sizes (64px) the black outlines become 'invisible'. But actually I think they make the shape clearer and the borders between colours sharper. Perhaps turn them on to render at smaller sizes?

**Comment by zsilencer** [comment]
![untitled-6](https://cloud.githubusercontent.com/assets/5456638/6200887/0ff139ea-b44a-11e4-9b0c-3eefef13ae33.png)

**Comment by xzbobzx** [comment]
I know why it looks out of place!

This:
![icon](http://i.imgur.com/N1BbGiM.png)

is not this:
![rct2](http://i.imgur.com/wEqRVC6.png)

I can try to recreate that original slide exactly the way it is, but it will take a while, and it won't be original. Anyone got ideas?

**Comment by IntelOrca** [comment]
@xzbobzx Recreating it is fine.

**Comment by runelaenen** [comment]
Any news concerning the logo?

**Comment by xzbobzx** [comment]
Yeah I'll try recreating the original slide. I doubt I can get it to look exact though, but we'll see.

**Comment by IntelOrca** [comment]
@xzbobzx Aim for better than original rather than exact.

**Comment by xzbobzx** [comment]
I'll do my very best.

**Comment by yayachiken** [comment]
Wouldn't this give you copyright issues?

Recreating from memory should be fine, but actually tracing the original would make the new logo a derived work. Therefore it is impossible to release the new logo under a free license since the original is most likely All Rights Reserved, and a derived work is already copyright infringement...

**Comment by IntelOrca** [comment]
This slide design is not explicitly copyright, OpenTTD practically mimed all the graphics from the original game. Its a Helter Skelter, I don't think its would be at all easy for a copyright case to be filed over this...

**Comment by yayachiken** [comment]
That's not how copyright works unfortunately.

See also that OpenTTD explicitly mandated:
> The graphics should be a similar but distinct version of the object in question - no graphics may be copied at all from the original.

[(Source)][1]

As I said, recreating from memory is (probably) fine, but tracing creates a derived work.

This is also how I know it from other projects like OpenStreetMap. There it is fine to use existing maps for sanity checks, but you may never use existing maps as a source to correct the data, as this would introduce copyright issues, because your corrections are derived works of the source you used.

As for potential lawsuits: Yes, the probabilty for a case is slim, but in most cases, you would only get a cease & desist anyway, and the burden to fight this in a court of law would be on your side, and you would probably have to scrap the project to avoid further trouble.

Apropos C&D: The most likely artwork to induce such a letter would probably be the OpenRCT logo with the wavy text, as this looks *very* similar to the trademarked RCT2 logo. Weakening the trademark is something the companies are most likely not going to accept.

After all please be aware that I am not trying to put a roadblock in your way, I just want to make you aware of the legal problems that can arise from these little things. Even your disassembly of the code has at least *some* protections at least under EU law which may give you enough wiggle-room to make it not rewarding for a legal team to pursue, but clear copyright or trademark infringement certainly does not and one can hit you hard with no risk of being in the wrong.

[1]: https://wiki.openttd.org/Graphics_Replacement#Contributer_Guidelines

**Comment by IntelOrca** [comment]
If @xzbobzx was to not show any evidence of tracing then you could not prove that it was traced. Of course you could also draw a new version based on the traced version too. If we are asked to change the logo for copyright reasons, then we can do so.

**Comment by yayachiken** [comment]
As I said, this is not how it works. Here is a [read on the topic][1], this is US law but it doesn't really matter in this case. As you can see, these pictures were also not traced, just copied too closely to the original.

[1]: http://99designs.com/designer-blog/2013/04/19/5-famous-copyright-infringement-cases/

**Comment by xzbobzx** [comment]
How is OpenTTD legal anyway? And for that matter OpenRCT2.

We're basically copying an entire game exactly, save for a few extras here and there, and it (OpenTTD) is given away free. I don't see how that's legal?

Not that I mind, OpenTTD is great fun. I just find it a bit weird.

**Comment by xzbobzx** [comment]
Done.

1024:
![1024](http://i.imgur.com/dRbRcNP.png)

64:
![64](http://i.imgur.com/oaoKNYD.png)

48:
![48](http://i.imgur.com/hWiy4DL.png)

32:
![32](http://i.imgur.com/7BsviiI.png)

16:
![16](http://i.imgur.com/vCk7wj6.png)

What do you think?

**Comment by IntelOrca** [comment]
Looking good, although the slide looks like a thin ribbon at the moment. Shouldn't the bottom of the slide look shiny as well on the right hand side of the image to give an impression of a floor? It also loses its depth when over the centre of the image. The structure seems fine though.

**Comment by xzbobzx** [comment]
Hmm you're quite right. Let me see what I can do about that.

**Comment by xzbobzx** [comment]
How's this?

![new1024](http://i.imgur.com/IbAuTF0.png)

link: http://i.imgur.com/IbAuTF0.png
link to old one: http://i.imgur.com/dRbRcNP.png

**Comment by mrtnptrs** [comment]
Looks better (actually it looks great!), but the shadows (especially at the top of the slide) are currently completely wrong :)

**Comment by zsilencer** [comment]
You should add highlights as well to make it look shiny

**Comment by xzbobzx** [comment]
How's this?

![take3](http://i.imgur.com/mzvuuju.png)

link: http://i.imgur.com/mzvuuju.png

**Comment by zsilencer** [comment]
I was thinking more like this kind of stuff, and add in reflections too
![687474703a2f2f692e696d6775722e636f6d2f576b4b6a3367462e706e67](https://cloud.githubusercontent.com/assets/5456638/6254796/6d840878-b768-11e4-8e2d-55a747803851.jpg)

**Comment by xzbobzx** [comment]
I can try something like that.

I'm not sure if it's the look we're after, but it's worth a shot.

**Comment by PFCKrutonium** [comment]
The reflection on the underside of the slide looks like you can see through the slide.

**Comment by xzbobzx** [comment]
How's this?

![specular](http://i.imgur.com/QKzcvYk.png)

Basically just what zsilencer did.

**Comment by Wopian** [comment]
Comparison of the rct2 colour palette one (left) and original colours (right):

[codepen url="http://codepen.io/Wopian/pen/xbWajJ" height="500" type="result"]

**Comment by IntelOrca** [comment]
That is quite a good colour match!

**Comment by xzbobzx** [comment]
New version, using @Wopian's colors:

1024px:
![new](http://i.imgur.com/zOIfWRA.png)

link: http://i.imgur.com/zOIfWRA.png
link to 245 color version: http://i.imgur.com/oj4DXYb.png
link to previous colors: http://i.imgur.com/3uiWXA2.png

**Comment by ThomasdenH** [comment]
I really like it! How does the color palette version look in smaller formats?

**Comment by xzbobzx** [comment]
64, 32, and 16 pixels respectively:

![multiples](http://i.imgur.com/oe0UzmE.png)

I think that looks pretty neat.

**Comment by zsilencer** [comment]
That was cool
I'm excited for it

**Comment by xzbobzx** [comment]
Yeah I'm happy with how it turned out.

I might need to do a few small tweaks here and there, but in my opinion this thing's ready to ship.

**Comment by IntelOrca** [comment]
@xzbobzx My last feedback would be
* make the windows look more inset (at the moment they just looked painted on)
* make the top of the slide looker thicker and closer to the structure (at the moment it looks like its coming away from the structure and getting thinner)

Other than that, I am happy with it.

**Comment by xzbobzx** [comment]
Awesome, I'll get to work right away.

**Comment by xzbobzx** [comment]
How's this?

1024px:
![1024](http://i.imgur.com/U9GbEXL.png)

64px:
![64](http://i.imgur.com/GphpDaw.png)

32px:
![32](http://i.imgur.com/wlM1hdS.png)

I lowered the whole helter skelter by a small bit, made the top slide thicker, and gave the windows a more indented look.

**Comment by IntelOrca** [comment]
Inset them more and add the flag (on top of the diamond).

**Comment by xzbobzx** [comment]
The flag will make the entire thing smaller. Is that okay?

**Comment by IntelOrca** [comment]
Have to see what its like, I think the flag should only be on the large version.

**Comment by xzbobzx** [comment]
Here's a new indentation try. What do you think?

![test](http://puu.sh/g6zCi/3a59f7a016.jpg)

**Comment by IntelOrca** [comment]
Yeah, that works.

**Comment by xzbobzx** [comment]
I now have these:

![bla](http://puu.sh/g6Cov/1a7c774b00.jpg)

Close-up of the flag:

![flag](http://puu.sh/g6Cr6/f33b5cb924.jpg)

**Comment by IntelOrca** [comment]
Yeah, that's great!

**Comment by xzbobzx** [comment]
Really? Sweet!

Shall I drop the SVGs in my dropbox?

**Comment by IntelOrca** [comment]
Export the svg to 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048 png and provide links including the original SVG of both with and without the flag.

**Comment by xzbobzx** [comment]
I really doubt how useful the 4px version is, haha:
![lol](http://puu.sh/g7Sfx/b132a3aa9d.png)

Anyway, all done. I've zipped it all up into a folder:
https://www.dropbox.com/s/rfzr1f11vre7jw7/OpenRCT2%20Icon.zip?dl=0

pngs ranging from 4 to 2048, plus SVG files of the both the flag version and the sans flag version.

**Comment by IntelOrca** [comment]
@xzbobzx Thanks, the logo and icon is finalised and in the repository.

**Comment by xzbobzx** [comment]
Sweet! I was glad to help.

**Comment by Gymnasiast** [comment]
Only one thing to do now: rip out the old RCT2 from the title sequence and stick the new one there :P

**Comment by mrtnptrs** [comment]
And add the icon to the executable :)

**Comment by xzbobzx** [comment]
I can't wait :D

**Comment by PFCKrutonium** [comment]
@zsilencer Can I use your logo on https://github.com/PFCKrutonium/OpenRCT2Launcher/ ?

**Comment by Scrumilation** [comment]
All this 3dness made me think of how good a low poly version of the selected logo would look, it just looks like a perfect model to be low-poly'd with some nice lighting and stuff
