### ISSUE TITLE
Broken screen scrolling with small map sizes

### ISSUE THREAD

**Issue by adrian17** [IntelOrca/OpenRCT2#772]
Video: http://puu.sh/fKcGB/ad5a4453f4.mp4

Depends on terrain height and map size; I can reproduce it with map sizes from 16 (on normal height) to 22 (on max height).

**Comment by duncanspumpkin** [comment]
I have a fix for this but I don't really like the solution. 
https://github.com/duncanspumpkin/OpenRCT2/tree/fix_scroll

The problem occurs due to the height being greater than the map size. This causes the function that moves the viewport to start accessing invalid map data. The invalid map data has been set to default height of 2 so the viewport tries to move down but then hits the edge and moves up triggering the loop again.
