### ISSUE TITLE
Navigation to different directories in load/save window

### ISSUE THREAD

**Issue by AaronVanGeffen** [IntelOrca/OpenRCT2#797]
While I love having the load/save window in-game, the current implementation appears to make it impossible to navigate to a different save directory. I feel this should be implemented as well.

**Comment by duncanspumpkin** [comment]
Yeah I agree should add ability to save to folders and also change folders. Could probably do it by adding a little up folder button and add ability to see folders.

**Comment by IntelOrca** [comment]
It should also probably allow you to load scenarios and saved games as well as landscapes in the scenario editor.

It should display details the saved game you are currently hovering over.

It might be worth having a button which still allows you to access the native operating system's file dialog (particularly if you want to access network drives etc.)

I wasn't able to implement "convert saved game to scenario" because the window can not replace the blocking file open dialog like before easily.

**Comment by Gymnasiast** [comment]
Having the list in alphabetical order would also be nice.

**Comment by IntelOrca** [comment]
@Gymnasiast What operating system are you using?

**Comment by IntelOrca** [comment]
I currently want to focus on fixing the bugs and implementing more code, so it would be really helpful if someone besides me added directory browsing to this dialog (I have done the tedious part... :p).

**Comment by Gymnasiast** [comment]
I'm using Ubuntu 14.04, with OpenRCT2 running via Wine.
![listorder](https://cloud.githubusercontent.com/assets/1478678/6203367/b9569226-b51e-11e4-8e8c-848e6d6ed4cf.jpg)

**Comment by IntelOrca** [comment]
@Gymnasiast OK, Windows actually automatically sorts the filenames when enumerating them. I'll have to manually sort them.
