### ISSUE TITLE
Issues with sound options

### ISSUE THREAD

**Issue by adrian17** [IntelOrca/OpenRCT2#809]
- currently disabling both music and sound doesn't work on all sounds - rain, toilet and notification sounds are still playing
- neither music nor sound settings are saved in the config file
- (side note: `g_sounds_disabled` doesn't actually do anything currently, it's only checked in the options window. Also see the note [here](https://github.com/IntelOrca/OpenRCT2/blob/develop/src/audio/audio.h#L226).)
- ~~it's weird to have music option as a dropdown, and sound as a checkbox; I think they both should be checkboxes (or a single dropdown with multiple options?)~~ changed in c4f1fa3b0c0507cfc771468d054b08dfec397143

**Comment by IntelOrca** [comment]
I also think sound quality should be ditched... does anyone still really require low or medium?

**Comment by PFCKrutonium** [comment]
lol no... Any computer made in the decade since RCT2 was released should be fine.

**Comment by duncanspumpkin** [comment]
Yeah sound quality just controls how many in total sounds can be heard at the same time. I think even at max its something like 8. It could easily be removed but no point doing it right now if it is a hassle.

**Comment by Gymnasiast** [comment]
The global sound on/off switch could be moved to the top of the sound settings dialog window, with the other settings as suboptions, since the other settings have no effect if the sound is turned off entirely. (Of course, the option would have to work in the first place.)

Also, changing the Music dropdown to a checkbox looks like a good idea to me.

And the low and medium can go, even my 1998 computer with half(!) the minimum specified RAM was able to run RCT2 with high sound quality. But if high sound quality is only 8 sounds at once, we could consider calling that 'low quality' and add options for even more. On the other hand, that might make the game a bit noisy.

**Comment by adrian17** [comment]
Separate volume sliders would be useful, one for "master volume" and the rest for specific sounds like music, guest sounds, ride sounds, environment (rain)... that would require implementing completely new widget type, but seems to be like a good end goal.

**Comment by RollingStar** [comment]
We could keep the low/medium/high functionality with an integer textbox for the number of sounds, if so desired. I personally don't need the feature, but maybe @Gymnasiast is right, and having (ex.) 128 sounds at once is too noisy. I always assumed they were picked based on distance from the player's current viewport.

Re: @adrian17's suggestion: Windows has built-in volume sliders as of Windows 7 (or Vista?). If it's possible to keep the game cross-platform and use those Windows sliders, I'd prefer that.

**Comment by Gymnasiast** [comment]
@RollingStar: RCT(2) uses its own controls, not OS-provided ones. Using an OS-provided one (even if it's cross-platform) would look out of place. OpenRCT2 got rid of the OS-provided rename and load/save dialogs for this reason.

**Comment by AaronVanGeffen** [comment]
With OpenRCT2's viewport being much larger than RCT2's, thereby making more rides visible, I like the idea of being able to /hear/ those rides as well. Playing more sounds simultaneously has its obvious drawbacks, however. Perhaps the mixer could adjust the SFX volume depending on e.g. the distance of the ride to the centre of the viewport, or even the cursor?

**Comment by PFCKrutonium** [comment]
I would prefer the center of the view port, I've played games where it was based on the mouse, and it is just honestly annoying.

**Comment by zsilencer** [comment]
I don't think the sound quality option even does anything atm except for "other sounds", theres a couple of compile constants for max simultaneous sounds of vehicles and ride music.  The reason some sounds are still appearing when you choose to disable is because parts of the original game are still playing those.  The rain needs fixed though, I notice it also doesn't start to play when loading a save game that is raining.
